import { AnalyticsResponse, GetSingleQuestionRes } from "./apiReqRes";

export type Util = {
  _id: string;
  createdAt: Date;
  updatedAt: Date;
};

export type Question = Util & {
  title: string; // title of the question, created by user
  slug: string; // URL slug, generated by title and _id
  markdown: string; // markdown content, created by user
  userId: string; // id of the user who created this question
  answerIds: string[]; // list of answers to this question, updated when adding answers
  level: string;
  subject: string;
  upvotes: number; // number of upvotes, updated when adding upvotes
  downvotes: number; // number of downvotes, updated when adding downvotes
};

export type QuestionTableData = GetSingleQuestionRes & { key: string };

export type Answer = Util & {
  markdown: string;
  userId: string; // id of the user who created this question
  upvotes: number;
  downvotes: number;
  questionId: string;
};

export enum Level {
  //ranked in increasing age
  PRIMARY = "Primary",
  SECONDARY_EXPRESS = "Secondary Express",
  SECONDARY_NA = "Secondary Normal Academic",
  SECONDARY_NT = "Secondary Normal Technical",
  JUNIOR_COLLEGE = "Junior College",
  IB = "International Baccalaureate",
  POLYTECHNIC = "Polytechnic",
  ITE = "ITE",
  UNIVERSITY = "University",
  BACHELOR = "Bachelor",
  MASTERS = "Masters",
  PHD = "PhD",
  DEFAULT = "Others",
}

export enum Subject {
  //STEM
  ENGLISH = "English",
  CHINESE = "Chinese",
  MATHEMATICS = "Mathematics",
  SCIENCE = "Science",
  PHYSICS = "Physics",
  CHEMISTRY = "Chemistry",
  BIOLOGY = "Biology",
  ENGINEERING = "Engineering",
  HEALTHCARE = "Healthcare",
  STEM = "STEM",
  COMPUTING = "Computer Science",
  MEDICINE = "Medicine",
  //ARTS, HUMANITIES AND SOCIAL SCIENCES
  HISTORY = "History",
  GEOGRAPHY = "Geography",
  ART = "Art",
  MUSIC = "Music",
  LITERATURE = "Literature",
  SOCIOLOGY = "Sociology",
  SOCIAL_STUDIES = "Social Studies",
  ARTS_HUMANS = "Arts and Humanities",
  //RANDOM
  BUSINESS = "Business",
  LAW = "Law",
  EDUCATION = "Education",
  GENERAL_PAPER = "General Paper",
  PW = "Project Work",
  COOK = "Culinary Arts",
  GENERAL = "General",
  DEFAULT = "Others",
}

export type User = Util & {
  username: string;
  email: string;
  answerIds: string[];
  questionIds: string[];
  answers?: Answer[];
  questions?: Question[];
  analytics?: AnalyticsResponse;
};
