export enum Subject {
  //STEM
  ENGLISH = "English",
  CHINESE = "Chinese",
  MATHEMATICS = "Mathematics",
  SCIENCE = "Science",
  PHYSICS = "Physics",
  CHEMISTRY = "Chemistry",
  BIOLOGY = "Biology",
  ENGINEERING = "Engineering",
  HEALTHCARE = "Healthcare",
  STEM = "STEM",
  COMPUTING = "Computer Science",
  MEDICINE = "Medicine",
  //ARTS, HUMANITIES AND SOCIAL SCIENCES
  HISTORY = "History",
  GEOGRAPHY = "Geography",
  ART = "Art",
  MUSIC = "Music",
  LITERATURE = "Literature",
  SOCIOLOGY = "Sociology",
  SOCIAL_STUDIES = "Social Studies",
  ARTS_HUMANS = "Arts and Humanities",
  //RANDOM
  BUSINESS = "Business",
  LAW = "Law",
  EDUCATION = "Education",
  GENERAL_PAPER = "General Paper",
  PW = "Project Work",
  COOK = "Culinary Arts",
  GENERAL = "General",
  DEFAULT = "Others",
}
