import { type } from 'os'

export type Question = {
  id: string
  createdAt: Date
  updatedAt: Date
  title: string // title of the question, created by user
  slug?: string // URL slug, generated by title and _id
  markdown: string // markdown content, created by user
  userId: string // id of the user who created this question
  answerIds: string[] // list of answers to this question, updated when adding answers
  level: string
  subject: string
  upvotes: number // number of upvotes, updated when adding upvotes
  downvotes: number // number of downvotes, updated when adding downvotes
}

export type Answer = {
  id: string
  markdown: string
  upvotes: number
  downvotes: number
}
