import { ObjectId } from "mongodb";

import { Util } from "./Util";
import { Subject, Level } from "../utils";

export interface Question extends Util {
  title: string; // title of the question, created by user
  slug: string; // URL slug, generated by title and _id
  markdown: string; // markdown content, created by user
  userId: ObjectId; // id of the user who created this question
  answerIds: ObjectId[]; // list of answers to this question, updated when adding answers
  level: Level;
  subject: Subject;
  upvotes: number; // number of upvotes, updated when adding upvotes
  downvotes: number; // number of downvotes, updated when adding downvotes
}
